runtime: custom
env: flex

env_variables:
  NODE_ENV: 'production'
  NPM_BUCKET: 'npm-reg'
  NPM_REGISTRY: 'https://registry.npmjs.org'
  NPM_STORAGE: 'https://storage.googleapis.com'
  NPM_TIMEOUT: 3000
  NPM_TTL: 21600
