'use strict'

const { route, router } = require('../lib/router')
const { rm, add, ls } = require('./dist-tags')
const unpublish = require('./unpublish')
const publish = require('./publish')
const search = require('./search')
const access = require('./access')
const logout = require('./logout')
const owner = require('./owner')
const login = require('./login')
const info = require('./info')
const ping = require('./ping')
const team = require('./team')
const tar = require('./tar')

route('get', '/-/package/:name/collaborators', access.lsCollaborators)
route('post', '/-/package/:name/access', access.access)
route('delete', '/-/package/:name/dist-tags/:tag', rm)
route('put', '/-/package/:name/dist-tags/:tag', add)
route('get', '/-/package/:name/dist-tags', ls)
route('get', '/-/team/:scope?/:team/package', access.lsPackages)
route('put', '/-/team/:scope?/:team/package', access.grant)
route('delete', '/-/team/:scope?/:team/package', access.revoke)
route('get', '/-/team/:scope?/:team/user', team.ls)
route('put', '/-/team/:scope?/:team/user', team.add)
route('delete', '/-/team/:scope?/:team/user', team.rm)
route('delete', '/-/team/:scope?/:team', team.destroy)
route('put', '/-/org/:scope?/team', team.create)
route('get', '/-/user/(org.couchdb.user:)?:user', owner)
route('put', '/-/user/(org.couchdb.user:)?:user', login)
route('delete', '/-/user/token/:token', logout)
route('get', '/-/v1/search', search)
route('get', '/-/all', search)
route('get', '/-/ping', ping)
route('get', '/:name*/-/:scope/:filename/:sha?', tar)
route('delete', '/:name/(-rev)?/:rev?', unpublish)
route('put', '/:name/(-rev)?/:rev?', publish)
route('get', '/:name*', info)

module.exports = router
